#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x tint2 >/dev/null || tint2 &
pgrep -x picom >/dev/null || picom --experimental-backends &
# pgrep -x picom >/dev/null || picom -b &
pgrep -x dunst >/dev/null || /usr/bin/dunst &
pgrep -x fcitx >/dev/null || fcitx -dr &

livewallpaper &
volume &
unclutter &
numlockx &
xclip &
xset r rate 320 38 &
flameshot &
redshift-gtk &
xsetroot -cursor_name left_ptr &

bspc monitor -d 一 二 三 四 五

bspc config border_width 0
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true

bspc rule -a Spotify desktop='^3'
bspc rule -a Vlc desktop='^5'
bspc rule -a Obsidian desktop='^4'
bspc rule -a Inkspace desktop='^4'
bspc rule -a Zathura state=tiled
bspc rule -a Pcmanfm desktop='^1'

bspc rule -a mplayer2 state=floating
bspc rule -a feh state=floating

bspc rule -a Kupfer.py focus=on

bspc rule -a Screenkey manage=off
