#!/usr/bin/python3
import subprocess


def get_nvidia_usage():
    result = subprocess.run(
        ["nvidia-smi", "-q", "-g", "0", "-d", "UTILIZATION"],
        stdout=subprocess.PIPE,
    )
    return int(
        list(
            filter(
                lambda line: str(line).startswith("Gpu:"),
                map(
                    lambda line: str(line).strip().replace(" ", ""),
                    result.stdout.decode().splitlines(),
                ),
            )
        )[0]
        .split(":")[-1]
        .replace("%", "")
    )


if __name__ == "__main__":
    print(get_nvidia_usage())
