#!/usr/bin/python3
import subprocess


def get_nvidia_usage():
    result = subprocess.run(["nvidia-smi"], stdout=subprocess.PIPE)
    print(result.stdout.decode())

if __name__ == "__main__":
    get_nvidia_usage()
