#!/bin/sh

# Get Volume
get_volume() {
	is_mute=$(pactl get-sink-mute 0 | awk '{print $2}')

	if [[ "$is_mute" == "no" ]]; then
		volume=$(pactl get-sink-volume 0 | awk '{print $5}' | tr -d '%')
		echo "$volume"
	else
		echo "Mute"
	fi
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	is_mute=$(pactl get-sink-mute 0 | awk '{print $2}')

	if [[ "$is_mute" == "on" ]]; then
		if [[ "$current" -eq "0" ]]; then
			echo "ﱝ"
		elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
			echo "奄"
		elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
			echo "奔"
		elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
			echo "墳"
		fi
	else
		echo "ﱝ"
	fi
}

# Increase Volume
inc_volume() {
	pactl set-sink-volume 0 +2%
}

# Decrease Volume
dec_volume() {
	pactl set-sink-volume 0 -2%
}

# Toggle Mute
toggle_mute() {
	is_mute=$(pactl get-sink-mute 0 | awk '{print $2}')

	if [[ "$is_mute" == "no" ]]; then
		pactl set-sink-mute 0 toggle
	else
		pactl set-sink-mute 0 toggle
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi
