version = "1.1.7"

[class]
DEFAULT = " {class}: {title}"
"(?i)Kitty" = "term"
"(?i)waydroid.*" = "droid"
"[Ff]irefox" = "browser"

[class_active]
DEFAULT = "*{icon}*"
"(?i)ExampleOneTerm" = "<span foreground='red'>{icon}</span>"

[initial_class]

[initial_class_active]

[workspaces_name]
0 = ""
1 = "󰲠"
2 = "󰲢"
3 = "󰲤"
4 = "󰲦"
5 = "󰲨"
6 = "󰲪"
7 = "󰲬"
8 = "󰲮"
9 = "󰲰"
10 = "󰿬"

[title_in_class."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"" = "^$"
"[Ss]team" = "^(Friends List.*)?$"
aProgram = "^$"
"(?i)TestApp" = ""

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{name}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "*{icon}*"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
