abbr mv "mv -i"
abbr cp "cp -i"
abbr rm "rm -i"
abbr mkdir "mkdir -p"

abbr ack "sk -i -c 'rg --color always --line-number "{}"'"
abbr du "dust"
abbr ps "procs --sortd cpu"
abbr ls "exa -lag --header"
abbr open "bat"
abbr awk "frawk"
